import { createPortalConfig } from '@nocobase/dev-config/eslint';

export default createPortalConfig({
  tsconfigRootDir: import.meta.dirname,
  ignores: [
    '.extension-state/**',
    'client-old/**',
    'public/r/**',
    'storage/**',
    // Generated snapshot seed: its exact bytes are the checksum recorded in the
    // seed history of every database that ran it, so formatting must not change it.
    'database/main/seeds/202609220007_seed_curated_tracker_snapshot.ts',
  ],
  overrides: [
    {
      // shadcn's chart primitive is generated by the CLI and leans on Recharts'
      // loose payload types; satisfying the type-aware rules here would mean
      // hand-rewriting it and diverging from the registry copy.
      files: ['client/components/ui/chart.tsx'],
      rules: {
        '@eslint-react/dom-no-dangerously-set-innerhtml': 'off',
        '@eslint-react/no-array-index-key': 'off',
        '@typescript-eslint/no-unsafe-argument': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/restrict-template-expressions': 'off',
      },
    },
  ],
});
