import { authenticationToken } from '@nocobase/app-plugin-authentication';
import {
  defineFileRepositoryApiRoutes,
  type FileRepositoryApiActions,
} from '@nocobase/app-plugin-file/server';
import { Hono } from 'hono';

/**
 * Images pasted into a problem description or comment. See
 * `database/main/migrations/202609220005_create_problem_images.ts`.
 */
const FILE_RESOURCE = 'problemImages';
const FILE_COLLECTION = 'problem_images';
const FILE_ACCESS_PATH = '/uploads/problems';
const FILE_ACTIONS: FileRepositoryApiActions = {
  uploadOne: { maxSize: 5 * 1024 * 1024 },
};

const fileRoutes = defineFileRepositoryApiRoutes({
  repositories: [
    {
      name: FILE_RESOURCE,
      collection: FILE_COLLECTION,
      connection: 'main',
      disk: 'local',
      accessPath: FILE_ACCESS_PATH,
      accessMode: 'stream',
      // Uploads bind the create scope and the file columns; reads and deletes stay
      // closed because the UI never lists or removes an uploaded image on its own.
      policy: { read: true, create: true, update: false, delete: false },
      actions: FILE_ACTIONS,
    },
  ],
});

/**
 * The File plugin's routes are public by design: the generated byte route serves
 * anyone holding a UUID, and the upload action has no identity of its own. This is
 * an internal tracker, so both paths require a session before reaching them.
 *
 * Middleware is registered for the exact paths this contribution owns. A
 * `router.use('*', ...)` here would guard every contribution mounted after it,
 * because contributions share the mounted router.
 */
type FileRouteContribution = ReturnType<
  typeof defineFileRepositoryApiRoutes
>[number];

function requireAuthentication(
  contribution: FileRouteContribution,
): FileRouteContribution {
  return {
    ...contribution,
    async createRouter(app) {
      const inner = await contribution.createRouter(app);
      const router = new Hono();
      const auth = app.container.resolve(authenticationToken);

      if (contribution.scope === 'api') {
        for (const action of Object.keys(FILE_ACTIONS)) {
          const path = `/${FILE_RESOURCE}:${action}`;
          router.use(path, auth.required());
        }
      } else {
        router.use(`${FILE_ACCESS_PATH}/:file`, auth.required());
      }

      router.route('/', inner);
      return router;
    },
  };
}

const problemFileRoutes: readonly FileRouteContribution[] =
  fileRoutes.map(requireAuthentication);

export default problemFileRoutes;
