import { defineSeed, type SeedDefinition } from '@nocobase/db';

/**
 * Curated tracker snapshot: the checklist the team works from today.
 *
 * The first import seeds carried the raw workbook; this snapshot is the curated
 * state that replaced it (readiness judgements, the Example acceptance rewrite,
 * owners, statuses and timeline). It runs once per database. On the deployment it
 * was added for it replaces what the earlier release had; on a fresh install it
 * seeds this dataset;  a database that already ran it keeps its own edits.
 *
 * Deliberately destructive on its first run: delete the tracker rows, then write
 * the snapshot. The legacy `missing_items` table is left untouched — the
 * application no longer reads it.
 */
interface FeatureSeed {
  readonly name: string;
  readonly level: 'dimension' | 'feature';
  readonly dimension: string | null;
  readonly owner: string | null;
  readonly skillsStatus: string;
  readonly docsStatus: string;
  readonly exampleExists: string;
  readonly exampleExpected: string | null;
  readonly exampleCurrent: string | null;
  readonly status: string;
  readonly designScore: number | null;
  readonly designNote: string | null;
  readonly developmentScore: number | null;
  readonly developmentNote: string | null;
  readonly agentFriendlinessScore: number | null;
  readonly agentFriendlinessNote: string | null;
  readonly outputQualityScore: number | null;
  readonly outputQualityNote: string | null;
  readonly remark: string | null;
  readonly sortOrder: number;
}

interface ProblemSeed {
  readonly feature: string;
  readonly title: string;
  readonly description: string | null;
  readonly type: string;
  readonly status: string;
  readonly owner: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
}

interface ActivitySeed {
  readonly feature: string;
  readonly problemTitle: string;
  readonly kind: string;
  readonly actorName: string;
  readonly fromStatus: string | null;
  readonly toStatus: string | null;
  readonly createdAt: string;
}

const FEATURES: readonly FeatureSeed[] = [
  {
    name: "应用安装",
    level: "dimension",
    dimension: null,
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "5 个测试大维度之一",
    sortOrder: 0,
  },
  {
    name: "从 create app 开始，支持不同数据库",
    level: "feature",
    dimension: "应用安装",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "应用创建入口需支持不同数据库",
    sortOrder: 1,
  },
  {
    name: "什么时候 Agent 介入",
    level: "feature",
    dimension: "应用安装",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "明确 Agent 介入时机",
    sortOrder: 2,
  },
  {
    name: "应用部署",
    level: "dimension",
    dimension: null,
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "5 个测试大维度之一",
    sortOrder: 3,
  },
  {
    name: "build",
    level: "feature",
    dimension: "应用部署",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 4,
  },
  {
    name: "deploy",
    level: "feature",
    dimension: "应用部署",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：手动上传部署、cli 部署",
    sortOrder: 5,
  },
  {
    name: "回滚",
    level: "feature",
    dimension: "应用部署",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 6,
  },
  {
    name: "启动、重启、停止等",
    level: "feature",
    dimension: "应用部署",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "进程生命周期管理",
    sortOrder: 7,
  },
  {
    name: "应用升级",
    level: "dimension",
    dimension: null,
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "5 个测试大维度之一",
    sortOrder: 8,
  },
  {
    name: "代码更新",
    level: "feature",
    dimension: "应用升级",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 9,
  },
  {
    name: "多环境迁移",
    level: "feature",
    dimension: "应用升级",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 10,
  },
  {
    name: "应用搭建",
    level: "dimension",
    dimension: null,
    owner: "曾煌尧",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "create-app 三模板创建、目录与组合根、插件注册/卸载/更新、Skills 同步、自定义 CLI、dev/build/start/打包/跨平台、页面与子路由/覆盖层、服务生命周期、后台任务与调度、实时、工作流、扩展点（route override / registry）。",
    exampleCurrent: "组合根 client/runtime.ts、server/runtime.ts、client/routes.ts；路由与覆盖层最完整（client/routes.ts:33-101、pages/route-overlays/）；3 个应用自有工作流（server/workflows/）；11 个 packages/examples/ 插件示例；scheduler/queue/realtime/service-provider 服务端示例齐全。",
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "状态说明：可以测试（不代表完备）、重构中、进行中、延期\n[skills 依据 2026-09-22] nocobase-app-development（SKILL.md：组合根、插件注册/卸载/更新、skills:sync、CLI、route override + 16 篇 references + testing.md 验证）+ nocobase-app-upgrade（模板升级）\n[docs 依据 2026-09-22] 源码：模板 README.MD（383 行）+ AGENTS.md（360 行）；官网：cn/get-started/*（6 页）、cn/app/{pages-and-routes,components-and-styling,i18n}、cn/deployment/*（构建/发布/部署）；缺口：cn/plugin-development/*、cn/reference/{commands,configuration} 等仍是占位页",
    sortOrder: 11,
  },
  {
    name: "数据库",
    level: "feature",
    dimension: "应用搭建",
    owner: "陈霖",
    skillsStatus: "available",
    docsStatus: "missing",
    exampleExists: "yes",
    exampleExpected: "迁移 up/down、种子幂等、多连接、外部只读连接、Repository/Query、collections 元数据生成、方言、数据库浏览器、迁移回滚验证、编译清单。",
    exampleCurrent: "database/main 迁移+种子；analytics 独立连接（server/config/database.ts、database/analytics/*、server/routes/analytics.ts）；externalCrm 只读 + metadata.json（database/externalCrm/collections/*）；Repository 全能力（app-plugin-repository-example）；Query vs Repository（/numeric-examples）；Database Explorer 设置页；迁移回滚测试。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：migration、query、repository、collections\n[skills 依据 2026-09-22] nocobase-app-development/references/{migrations,database-and-data,database-connections}.md（均含 Verify）\n[docs 依据 2026-09-22] 源码：@nocobase/db README.zh-CN.md（106 行，含运行示例与验证）；官网：cn/app/database.md、cn/app/migrations.md 均标注「文档编写中」，无可用内容",
    sortOrder: 12,
  },
  {
    name: "认证",
    level: "feature",
    dimension: "应用搭建",
    owner: "杨洽",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "登录/登出/注册/忘记/重置、会话持久化与吊销、安装向导、API Keys、路由 guard、SSO、邮件流程。",
    exampleCurrent: "登录登出注册、忘记/重置页、auth: guest/required guard、会话存库、API Keys（root 可开 /settings/api-keys）、初始管理员 seed（nocobase/admin123）。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "[skills 依据 2026-09-22] nocobase-app-plugin-authentication（Verification 章节）\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-authentication README.zh-CN.md（包入口/页面归属/配置）；官网：cn/capabilities/auth/*（index、quick-start、development 4 篇）",
    sortOrder: 13,
  },
  {
    name: "授权",
    level: "feature",
    dimension: "应用搭建",
    owner: "杨洽",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "权限集/用户管理、页面级/API 级授权、默认访问/共享/限制规则、数据行/字段级、即时生效、未授权语义、审计。",
    exampleCurrent: "app-plugin-authorization-example 完整业务演示（4 页 + 字段白名单 + 行 scope + 团队共享 + 三类规则种子；账号 sales_* / AuthzExample123!）；权限集、用户管理、Inspector 均已注册；authz: 'skip' 与页面拒绝可演示。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "[skills 依据 2026-09-22] nocobase-app-plugin-authorization（Completion evidence）+ authz-* 三个子 skill\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-authorization README（256 行，API map/声明/执行）；官网：cn/capabilities/authorization/*（8 页，含 inspector 查验入口）",
    sortOrder: 14,
  },
  {
    name: "文件",
    level: "feature",
    dimension: "应用搭建",
    owner: "龚诚",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "存储盘、文件集合、单/批上传、预览、缩略图、1:1/1:N 关联、访问控制、可复用组件。",
    exampleCurrent: "/file-repository 三页（附件上传、头像 1:1、订单 1:N）；预览支持位图/PDF/文本/音视频 + DOCX/XLSX/PPTX 本地渲染；缩略图（前端原图缩放）。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "[skills 依据 2026-09-22] nocobase-app-plugin-file（Verify：小上传→元数据→内容下载）\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-file docs/README.md（292 行手册：路由/Service/客户端 Hook/限制）；官网：cn/capabilities/file.md（118 行）",
    sortOrder: 15,
  },
  {
    name: "AI 员工",
    level: "feature",
    dimension: "应用搭建",
    owner: "陈庚扬",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "插件注册、设置页、员工 CRUD、内置员工、聊天、工具/技能、MCP、放置形态、页面上下文、开箱可跑。",
    exampleCurrent: "插件已注册（client/server）；Settings→AI 管理页（Employees/Skills/Tools/Conversations）；开发态 /dev/ai-components/* 组件演示（现在配了 LLM 可真实对话）；内置员工 Atlas。",
    status: "testCompleted",
    designScore: null,
    designNote: null,
    developmentScore: 6.5,
    developmentNote: "74 个场景通过 47、未通过 27",
    agentFriendlinessScore: 6,
    agentFriendlinessNote: "资料评分 60/100（80 分算达标）；Agent 能完成主要任务，但有些步骤要自己翻源码或绕路才能走通，这些问题已整理反馈给开发",
    outputQualityScore: 7,
    outputQualityNote: "生成的应用能用：开发环境和正式打包后都跑通了真实问答；但正式包第一次不完整（缺个依赖、补上才能启动），代码检查有不少不规范项，也没写自动化测试",
    remark: "环境已解决：已把 app/ai-test/config.yml 的 ai.llmServices（dashscope-test：qwen3.7-flash + text-embedding-v4）写入模板 config.yml（gitignored，未改源码）。重启后实测：启动日志 llmServices:1；llmServices:list 正常；ai:listProviderModels 真实调通 DashScope；aiEmployees:list 返回 Atlas。原先“无预置 LLM”属环境问题，不计入模板缺口。\n[skills 依据 2026-09-22] nocobase-app-plugin-ai-employee（Verification Checklist）\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-ai-employee README（110 行：入口/LLM/MCP/会话/Skills/工具）；官网：cn/capabilities/ai-employee/**（20 页）",
    sortOrder: 16,
  },
  {
    name: "知识库",
    level: "feature",
    dimension: "应用搭建",
    owner: "陈庚扬",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "no",
    exampleExpected: "插件注册与前置依赖、向量库、Embedding、知识库 CRUD、文档上传/管理、分段、命中测试、Manifest、RAG 绑定。",
    exampleCurrent: "开源 Examples 无 example：app-plugin-ai-knowledge-base 已整体移出开源（commit 741d0eba，2026-09-09），Examples 无依赖、无注册、无页面、无配置，git ls-files 为 0。Pro 版本无实例：code-pro 只有 packages/{examples,plugins} + vendor/nocobase3，没有任何应用模板/示例应用；知识库仅有插件包与 /dev/ai-knowledge-base/* 插件内 dev 路由和 fixtures，要跑必须自行注册进新建应用，并配 PGVector + Embedding 模型 + queue。",
    status: "testCompleted",
    designScore: null,
    designNote: null,
    developmentScore: 7.5,
    developmentNote: "108 个场景通过 88、未通过 20",
    agentFriendlinessScore: 6,
    agentFriendlinessNote: "资料评分 60/100（80 分算达标）；缺口主要是功能规则和权限说明不清楚，Agent 有些地方要自己翻源码，问题已整理反馈给开发",
    outputQualityScore: 6.5,
    outputQualityNote: "应用能用：正式打包后能启动，真实上传文档、检索、问答都跑通；扣分原因：第一次打的正式包缺依赖、旧数据升级和带专业版插件的组合仍走不通、部署后的页面操作还没验收",
    remark: "开源无；Pro 无实例，仅插件包 dev 路由\n[skills 依据 2026-09-22] code-pro/packages/plugins/app-plugin-ai-knowledge-base/skills/nocobase-app-plugin-ai-knowledge-base（skill 1.0.0 / plugin 0.1.0-beta.6 / code-pro 0f8ff3d；14 篇 references + Verification Checklist）\n[docs 依据 2026-09-22] 源码：code-pro/packages/plugins/app-plugin-ai-knowledge-base README（85 行：声明式配置/构建/示例）；官网：cn/capabilities/ai-knowledge-base/**（6 页）",
    sortOrder: 17,
  },
  {
    name: "邮件",
    level: "feature",
    dimension: "应用搭建",
    owner: "陆建浩",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "SMTP/Resend 配置、真实发送、测试发送、通知日志、收件人解析、邮件模板、业务发送示例、验证/找回密码邮件、工作流邮件节点。",
    exampleCurrent: "通知运行时与 Email/IM Provider 定义已注册；/settings/notifications/logs 有常驻“Send test notification”和通知日志；In-app 可走通“发送→收件箱→日志”。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "[skills 依据 2026-09-22] nocobase-app-plugin-notification（in-app/email/im 通道 + delivery-diagnostics）\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-notification README（93 行：运行要求/配置与安全/测试端点）；官网：cn/capabilities/notification.md（287 行）",
    sortOrder: 18,
  },
  {
    name: "多语言",
    level: "feature",
    dimension: "应用搭建",
    owner: "曾煌尧",
    skillsStatus: "available",
    docsStatus: "available",
    exampleExists: "yes",
    exampleExpected: "双语、切换器、持久化与服务端同步、服务端翻译/回退、默认语言、清单检查、overrides、插值/复数、格式化。",
    exampleCurrent: "en-US/zh-CN 双端文件、语言切换器（禁用/隐藏逻辑）、切换持久化+通知服务端、overrides（Examples 独有增量）、插值、Intl 日期数字、i18n:check。",
    status: "testCompleted",
    designScore: null,
    designNote: null,
    developmentScore: 9,
    developmentNote: "51 个场景通过 49、未通过 1，另有 1 个按设计不执行",
    agentFriendlinessScore: 8.5,
    agentFriendlinessNote: "资料评分 85/100；扣分在命令写法不统一、默认语言在开发环境怎么生效没讲清，其他都达标",
    outputQualityScore: 8,
    outputQualityNote: "应用开发环境和正式环境都验证过：升级模板后正式包能启动，部署后语言切换和缺失文案的回落都正常；扣分原因：打包和代码检查各返工过一次",
    remark: "[skills 依据 2026-09-22] nocobase-app-plugin-i18n（切换语言确认文案跟随）\n[docs 依据 2026-09-22] 源码：@nocobase/app-plugin-i18n README（90 行：注册/配置/切换/端点）；官网：cn/app/i18n.md（230 行）+ cn/capabilities/i18n.md（101 行）",
    sortOrder: 19,
  },
  {
    name: "日志",
    level: "feature",
    dimension: "应用搭建",
    owner: "陈庚扬",
    skillsStatus: "available",
    docsStatus: "missing",
    exampleExists: "yes",
    exampleExpected: "级别、输出目标、轮转保留、主动打日志、请求日志、脱敏、运行日志查看、工作流日志、通知日志。",
    exampleCurrent: "server/config/logging.ts（file+console+request）；请求日志中间件；工作流节点日志落库 + 运行详情页；通知发送日志设置页；scheduled-log-job 主动打日志。",
    status: "developed",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：api 日志、system 日志；存储：本地 storage、线上 hub\n[skills 依据 2026-09-22] nocobase-app-development/references/services-and-jobs.md §Persistent logging\n[docs 依据 2026-09-22] 源码：@nocobase/logging README（配置/轮转/留存/脱敏）；官网：中英均无日志页面，无可用内容",
    sortOrder: 20,
  },
  {
    name: "工作流",
    level: "feature",
    dimension: "应用搭建",
    owner: "严俊羿",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "refactoring",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：DSL",
    sortOrder: 21,
  },
  {
    name: "通知",
    level: "feature",
    dimension: "应用搭建",
    owner: "陆建浩",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "refactoring",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：config、send",
    sortOrder: 22,
  },
  {
    name: "队列",
    level: "feature",
    dimension: "应用搭建",
    owner: "严俊羿",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "inProgress",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "异步任务",
    sortOrder: 23,
  },
  {
    name: "定时任务",
    level: "feature",
    dimension: "应用搭建",
    owner: "严俊羿",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "inProgress",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 24,
  },
  {
    name: "审计",
    level: "feature",
    dimension: "应用搭建",
    owner: "龚诚",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "deferred",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 25,
  },
  {
    name: "导入导出",
    level: "feature",
    dimension: "应用搭建",
    owner: "龚诚",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "deferred",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 26,
  },
  {
    name: "审批",
    level: "feature",
    dimension: "应用搭建",
    owner: "严俊羿",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "deferred",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: null,
    sortOrder: 27,
  },
  {
    name: "历史记录",
    level: "feature",
    dimension: "应用搭建",
    owner: "龚诚",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "deferred",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "记录变更 before after",
    sortOrder: 28,
  },
  {
    name: "备份",
    level: "feature",
    dimension: "应用搭建",
    owner: "陈霖",
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "deferred",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "待定",
    sortOrder: 29,
  },
  {
    name: "应用测试",
    level: "dimension",
    dimension: null,
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "5 个测试大维度之一（如何写用例）",
    sortOrder: 30,
  },
  {
    name: "测试 kit",
    level: "feature",
    dimension: "应用测试",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "功能点划分：createMockClient、createMockServer、createMockDatabase",
    sortOrder: 31,
  },
  {
    name: "如何写测试",
    level: "feature",
    dimension: "应用测试",
    owner: null,
    skillsStatus: "unspecified",
    docsStatus: "unspecified",
    exampleExists: "unspecified",
    exampleExpected: null,
    exampleCurrent: null,
    status: "unspecified",
    designScore: null,
    designNote: null,
    developmentScore: null,
    developmentNote: null,
    agentFriendlinessScore: null,
    agentFriendlinessNote: null,
    outputQualityScore: null,
    outputQualityNote: null,
    remark: "主要包括业务搭建过程中产生的代码，如何写测试",
    sortOrder: 32,
  },
];

const PROBLEMS: readonly ProblemSeed[] = [
  {
    feature: "应用搭建",
    title: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    description: "资料依据：get-started/create-app*.md、reference/commands.md。\n应有演示：用 create-app 建出 Default/Examples/Hub 任一模板后，按 README 启动即可打开登录页并进入首页。\n现状：模板可跑，但“三模板差异 + 建完即跑”没有可复现步骤（README 只列命令）。\n验证：`pnpm create @nocobase/app` 选模板后按 README 执行 dev/start。",
    type: "example",
    status: "fixing",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.656",
  },
  {
    feature: "应用搭建",
    title: "缺 plugin:register/unregister 的“注册前→后”演示（示例插件已全部注册）",
    description: "资料依据：README.MD#Plugins、app-development Skill（plugin:register/unregister）。\n应有演示：注册一个示例插件后入口出现、卸载后入口消失，能看到变化过程。\n现状：所有 app-plugin-*-example 都已注册，看不到前后差异。\n验证：`pnpm plugin:unregister @nocobase/app-plugin-routes-example` 后重启，观察菜单变化。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.668",
  },
  {
    feature: "应用搭建",
    title: "缺 skills:sync 的端到端演示（改插件 Skill → 同步到应用）",
    description: "资料依据：README.MD（Skills 同步）、app-upgrade Skill。\n应有演示：修改一个插件内的 Skill，执行 `pnpm skills:sync` 后 `.agents/skills/` 对应目录更新。\n现状：Examples 没有演示步骤或前后对比。\n验证：改 `packages/plugins/*/skills/*/SKILL.md` 后跑 `pnpm skills:sync`，diff `.agents/skills/`。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.680",
  },
  {
    feature: "应用搭建",
    title: "缺自定义 CLI 命令的演示（cli/commands 无示例命令）",
    description: "资料依据：AGENTS.md「The command line」、reference/commands.md。\n应有演示：`cli/commands/` 里有一个应用自有命令，`pnpm nocobase app <name>` 可执行，并在 README 说明。\n现状：模板未提供示例命令，只有标准命令集合。\n验证：`pnpm nocobase --help` 看 app 主题下是否有自有命令。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.693",
  },
  {
    feature: "应用搭建",
    title: "缺 build --tar / --target 的打包与跨平台演示（只有文字说明）",
    description: "资料依据：README.MD（打包与跨平台构建）、AGENTS.md。\n应有演示：一条可复现命令产出 `storage/exports/dist.tar.gz`，并给出目标平台（--target/--node-version）的用法与产物校验。\n现状：只停在文档描述，没有示例步骤或产物。\n验证：`pnpm build --tar` 后检查 `storage/exports/dist.tar.gz` 与 `dist/package.json` 的 nocobase.buildTarget。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.705",
  },
  {
    feature: "应用搭建",
    title: "缺 route-overrides 与 registry-example 的演示（覆盖为空、示例未注册）",
    description: "资料依据：client AGENTS（route-overrides 规则）、app-plugin-registry-example。\n应有演示：`client/route-overrides.ts` 有一条实际覆盖示例；registry-example 已注册且页面可访问。\n现状：`client/route-overrides.ts` 为空，app-plugin-registry-example 未注册（已核对模板 plugins 列表）。\n验证：注册后访问该插件页面，观察组件是否来自应用侧覆盖。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.716",
  },
  {
    feature: "应用搭建",
    title: "缺 queue / service-provider / realtime 的首页入口演示",
    description: "资料依据：services-and-jobs.md（队列/服务生命周期）、template-variants。\n应有演示：首页或菜单里有跳转入口（例如 /realtime、队列示例页），无需手工拼地址。\n现状：服务端示例齐全，但首页没有入口，/realtime 要手工输入地址。\n验证：打开首页寻找入口；对比 `client/routes.ts` 中已注册路由。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.727",
  },
  {
    feature: "数据库",
    title: "缺 collections 派生产物的演示（`collections:generate --check` 跑不起来）",
    description: "资料依据：database-connections.md（database/<conn>/collections/ 产物）、migrations.md。\n应有演示：`database/main`、`database/analytics` 下有生成产物，`pnpm collections:generate --check` 能验证“派生”关系。\n现状：两个连接都没有 collections/ 产物，--check 无法演示。\n验证：执行 `pnpm collections:generate --check`，观察是否报缺产物。",
    type: "example",
    status: "pending",
    owner: "陈霖",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.737",
  },
  {
    feature: "数据库",
    title: "缺非 SQLite 方言的演示（mysql/oracle/postgres 有依赖无配置）",
    description: "资料依据：database-connections.md（切换默认连接、方言字段与默认值）。\n应有演示：至少一个非 SQLite 连接可启动、可读写（可用仓库内 docker-compose）。\n现状：三个连接全为 SQLite；`db-mysql`/`db-oracle`/`db-postgres` 有依赖但没有配置与演示。\n验证：查看 `server/config/database.ts` 与 `docker-compose.yml`，或按文档切一次 PG 跑迁移。",
    type: "example",
    status: "pending",
    owner: "陈霖",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.751",
  },
  {
    feature: "数据库",
    title: "缺 database-example 的界面演示（只有迁移与种子）",
    description: "资料依据：app-plugin-database-example、database-and-data.md。\n应有演示：注册该示例插件后能看到可访问的页面或接口，展示迁移/种子/查询的用法。\n现状：示例只有迁移与种子，没有界面入口。\n验证：注册后打开应用，检查菜单与路由是否有该示例入口。",
    type: "example",
    status: "pending",
    owner: "陈霖",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.764",
  },
  {
    feature: "数据库",
    title: "缺编译清单（.manifest.json）的演示",
    description: "资料依据：migrations.md#Compiled migration and seed manifests。\n应有演示：`pnpm build` 后展示 `dist/database/main/{migrations,seeds}/.manifest.json` 的内容与校验作用。\n现状：模板没有演示产物或说明。\n验证：构建后查看 dist 下 manifest 文件，并尝试改动迁移触发校验失败。",
    type: "example",
    status: "pending",
    owner: "陈霖",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.776",
  },
  {
    feature: "认证",
    title: "缺找回密码的实际发送演示（接口返回 400 RESET_PASSWORD_DISABLED）",
    description: "资料依据：app-plugin-authentication Skill（密码重置）、cn/capabilities/auth/*。\n应有演示：配置邮件发送后走通“请求重置 → 收邮件 → 重置密码 → 新密码登录”。\n现状：`server/config/auth.ts` 没有 `sendResetPassword`，实测 `POST /main/api/auth/request-password-reset` 返回 400 RESET_PASSWORD_DISABLED。\n验证：对已注册邮箱调用该接口，观察状态码与邮件。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.790",
  },
  {
    feature: "认证",
    title: "缺邮箱验证/邀请的演示",
    description: "资料依据：user-lifecycle-and-deployment.md（账号生命周期）。\n应有演示：注册后发送验证邮件并可完成验证，或管理员邀请用户加入。\n现状：模板完全没有该流程（无配置、无邮件、无页面）。\n验证：注册新账号后检查是否需要/能够验证邮箱。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.802",
  },
  {
    feature: "认证",
    title: "缺用户自助的多设备会话管理演示（现仅管理员“撤销全部”）",
    description: "资料依据：client-session-and-pages.md（会话与页面）。\n应有演示：用户可在账号页查看自己的登录会话并逐个注销。\n现状：只有管理员侧的会话撤销入口。\n验证：登录两个设备，检查用户端是否有会话列表与注销操作。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.814",
  },
  {
    feature: "认证",
    title: "缺 SSO/OIDC 的可用演示（组件已物化但零引用）",
    description: "资料依据：adding-sign-in-methods.md（第三方登录）。\n应有演示：注册一个 OIDC/SSO provider 后登录页出现对应按钮并能完成登录。\n现状：`client/extensions/nocobase-auth-ui` 里的 SSO 组件没有被任何页面引用，模板也未注册 provider。\n验证：打开登录页查看是否有第三方登录按钮。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.825",
  },
  {
    feature: "认证",
    title: "缺 auth: 'optional' 路由的演示",
    description: "资料依据：protecting-routes.md（auth: required/guest/optional）。\n应有演示：一条 `optional` 页面，未登录和已登录都能打开（内容按登录态变化）。\n现状：模板只有 guest 与 required 路由，没有 optional 示例。\n验证：查看 `client/routes.ts` 的 auth 取值。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.837",
  },
  {
    feature: "认证",
    title: "缺登录态修改密码的界面演示",
    description: "资料依据：client-session-and-pages.md、authentication Skill。\n应有演示：账号设置中可修改自己的密码，改完旧密码失效。\n现状：模板没有改密 UI。\n验证：登录后在账号菜单/设置中查找修改密码入口。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.850",
  },
  {
    feature: "认证",
    title: "缺 install 向导的演示（被预填 secret 绕过）",
    description: "资料依据：app-plugin-install、README.MD（首次启动）。\n应有演示：全新数据库首次启动进入 `/install` 向导完成初始化。\n现状：模板 `config.yml` 预填了 secret，安装向导被跳过。\n验证：用空数据库启动，观察是否进入 /install。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.862",
  },
  {
    feature: "授权",
    title: "缺模板自有 API 的授权演示（只有 auth.required()）",
    description: "资料依据：app-plugin-authorization Skill、runtime-api.md（authz.middleware / require）。\n应有演示：articles / numeric-examples / external-crm / analytics 中至少一个接口带资源与动作校验，越权返回 403。\n现状：这些接口只装 `auth.required()`，任何登录用户都能调用。\n验证：用无权限账号调用其中一个写接口，观察是否被拒。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.875",
  },
  {
    feature: "授权",
    title: "缺普通注册用户的可用角色演示（member 权限集 grants 为空）",
    description: "资料依据：cn/capabilities/authorization/permission-sets.md。\n应有演示：新注册用户有默认可用的页面与操作，登录后不是满屏 403。\n现状：member 权限集 grants 为空，除 root 外多数页面被拒。\n验证：注册一个新账号登录，检查可访问页面。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.887",
  },
  {
    feature: "授权",
    title: "缺“改授权→另一会话立即生效”的可操作演示",
    description: "资料依据：app-plugin-authorization Skill（notifyAssignmentsChanged、权限刷新）。\n应有演示：一个会话修改权限集后，另一个已登录会话无需重新登录即按新权限表现。\n现状：只有组件测试覆盖，模板里没有可操作演示。\n验证：两个浏览器会话分别登录，改权限后刷新另一会话观察结果。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.899",
  },
  {
    feature: "授权",
    title: "缺安全事件审计查询的演示（事件只写文件）",
    description: "资料依据：app-plugin-authorization Skill（安全事件）。\n应有演示：授权/账号相关安全事件可在界面查询（如设置页列表）。\n现状：安全事件只写日志文件，没有查询 UI。\n验证：触发一次授权变更，检查界面是否有记录入口。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.911",
  },
  {
    feature: "授权",
    title: "缺未授权场景的 e2e 演示",
    description: "资料依据：app/testing.md（测试方法）、authorization Skill（未授权语义）。\n应有演示：模板自带未授权 e2e（例如匿名/无权限访问返回 401/403）。\n现状：e2e 目录只有一条 AI 用例且默认 skip。\n验证：执行模板 e2e 脚本，观察覆盖范围。",
    type: "example",
    status: "pending",
    owner: "杨洽",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.923",
  },
  {
    feature: "文件",
    title: "缺非本地存储盘的演示（s3 为空占位，无 OSS/COS 驱动）",
    description: "资料依据：app-plugin-file Skill（disk 必填、访问路径与权限）。\n应有演示：至少一个非 local 的可用盘（S3/OSS/COS 或本地 S3 兼容服务）完成上传与读取。\n现状：只有 local 盘可用，s3 配置 `bucket: ''` 为空占位。\n验证：查看 `server/config/drive.ts`，或按文档配置一个 S3 兼容服务后上传。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.935",
  },
  {
    feature: "文件",
    title: "缺附件/存储管理页（v3 已明确移除，属设计变更）",
    description: "资料依据：app-plugin-file Skill / 历史文档。\n应有演示：若文档仍在描述“存储管理页”，需要同步文档或恢复演示。\n现状：v3 明确移除该页面，模板与插件都不提供。\n验证：对照当前 file 文档与设置页，确认文档是否仍描述已移除能力。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.947",
  },
  {
    feature: "文件",
    title: "缺服务端缩略图的演示（现仅前端原图缩放）",
    description: "资料依据：app-plugin-file Skill（缩略图/预览）。\n应有演示：上传大图后由服务端生成缩略图（或明确记录当前仅前端缩放）。\n现状：缩略图只是前端按原图缩放，大图仍全量下载。\n验证：上传大图观察网络请求体积与是否生成缩略文件。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.958",
  },
  {
    feature: "文件",
    title: "缺旧版 DOC/XLS/PPT 与 ODF 的本地预览演示（仅下载）",
    description: "资料依据：app-plugin-file Skill（预览矩阵：旧格式走 Office Online fallback）。\n应有演示：旧格式给出可用的预览回退或明确的下载说明与限制提示。\n现状：旧版 DOC/XLS/PPT 与 OpenDocument 只能下载。\n验证：上传一个 .doc 文件，观察预览行为与提示。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.970",
  },
  {
    feature: "文件",
    title: "缺 Examples 预置的 file component-ui 扩展（Default 有但未被引用）",
    description: "资料依据：app-plugin-file Skill（Registry component-ui）。\n应有演示：Examples 模板的 `client/extensions/` 里有 `nocobase-file-component-ui` 且被页面引用。\n现状：该扩展只在 Default 模板存在，Examples 未引用。\n验证：查看两个模板的 `client/extensions/` 与引用位置。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.983",
  },
  {
    feature: "文件",
    title: "缺文件 API 的鉴权示例（当前公开）",
    description: "资料依据：app-plugin-file Skill（内容路由默认公开，鉴权由应用负责）。\n应有演示：示例暴露文件资源时加上登录/权限校验（内容路由 + 上传接口），并演示匿名被拒。\n现状：模板文件示例没有鉴权示例，README 自述公开。\n验证：匿名请求示例文件内容路由，观察是否 200。",
    type: "example",
    status: "pending",
    owner: "龚诚",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:29.995",
  },
  {
    feature: "AI 员工",
    title: "缺生产态聊天入口的成品演示（三模板都未物化 AI Registry）",
    description: "资料依据：app-plugin-ai-employee Skill、cn/capabilities/ai-employee/components/*。\n应有演示：至少一种成品放置形态（页面内聊天、悬浮球或员工任务卡片）在模板页面里可用。\n现状：三个模板的 `client/extensions/` 只有 auth-ui，未物化 nocobase-ai Registry。\n验证：查看模板 `client/extensions/`，或打开页面找聊天入口。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.007",
  },
  {
    feature: "AI 员工",
    title: "缺示例员工/技能/MCP 的数据演示（ai/ 只有 .gitkeep）",
    description: "资料依据：ai-employee Skill（员工、技能、工具、MCP 配置）。\n应有演示：`ai/` 下带一个示例员工 + 技能（或工具/MCP），启动后设置页即可看到并可直接对话。\n现状：`ai/` 与 `ai/mcp/` 均为 `.gitkeep`。\n验证：启动应用后打开设置 → AI 员工，检查是否有模板自带员工。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.018",
  },
  {
    feature: "AI 员工",
    title: "缺首页/README 的 AI 能力条目",
    description: "资料依据：模板 README/首页应说明已启用的能力。\n应有演示：首页或 README 列出 AI 员工入口与配置方式。\n现状：首页与 README 没有 AI 相关条目。\n验证：打开首页与 README 查找 AI。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.030",
  },
  {
    feature: "AI 员工",
    title: "缺可默认跑通的 AI e2e（现默认 skip 且员工名不符）",
    description: "资料依据：app/testing.md、e2e 目录。\n应有演示：`pnpm test:e2e` 默认可跑通 AI 用例（不依赖手工配置），引用源码内置员工（atlas）。\n现状：`e2e/ai-local-server.test.ts` 默认 skip，且默认员工写的是 viz，与源码内置 atlas 不符。\n验证：执行 e2e，观察是否被跳过与引用的员工名。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.042",
  },
  {
    feature: "AI 员工",
    title: "缺发布产物包含 ai/ 骨架的保证（files 未含 ai/ 与 tsconfig.ai.json）",
    description: "资料依据：package.json files、模板发布说明。\n应有演示：打包发布后包含 `ai/` 骨架与 `tsconfig.ai.json`（或明确说明不需要）。\n现状：`files` 未包含 `ai/` 与 `tsconfig.ai.json`，且该 tsconfig 全仓库无引用。\n验证：`pnpm pack` 后解包检查文件清单。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.055",
  },
  {
    feature: "AI 员工",
    title: "缺五种员工放置形态的成品页（只有文档与 dev 组件）",
    description: "资料依据：cn/capabilities/ai-employee/components/{chat,context,floating,tasks,tool-cards}。\n应有演示：至少 1–2 种放置形态在模板页面里成品化（而不是只在 /dev/ai-components/*）。\n现状：只有开发态组件演示页。\n验证：打开模板页面，查找成品聊天/任务入口。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.067",
  },
  {
    feature: "邮件",
    title: "缺 SMTP/Resend 的可跑配置（config.yml 里只有注释）",
    description: "资料依据：app-plugin-notification Skill（email 通道）、cn/capabilities/notification.md。\n应有演示：启用一个 email provider（本地 SMTP 或 Resend）并完成一次真实发送。\n现状：`config.yml` 的 email 通道全是注释，没有可跑配置。\n验证：设置 → 通知日志页点“Send test notification”，观察是否因无 provider 失败。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.079",
  },
  {
    feature: "邮件",
    title: "缺业务代码调用通知服务的示例（无 notification.send() 调用）",
    description: "资料依据：sending-notifications.md（notificationServiceToken）。\n应有演示：示例服务/路由里调用通知服务发送一条消息（并处理 accepted 不等于送达）。\n现状：Examples 代码没有任何发送调用。\n验证：在模板源码里搜索 notificationServiceToken / send 调用。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.094",
  },
  {
    feature: "邮件",
    title: "缺邮件模板/HTML/附件与 resolveUserEmail 的演示",
    description: "资料依据：channel-and-provider-extensions.md、sending-notifications.md（收件人解析）。\n应有演示：一条带模板/HTML 或附件的邮件，以及按用户解析邮箱地址的用法。\n现状：没有模板、附件与 resolveUserEmail 示例。\n验证：配置 provider 后发送一封带 HTML 的测试邮件。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.106",
  },
  {
    feature: "邮件",
    title: "缺注册验证/找回密码邮件的演示（找回密码实测 400）",
    description: "资料依据：app-plugin-authentication Skill（账号生命周期）、notification Skill（email 通道）。\n应有演示：注册验证邮件与找回密码邮件可走通（配置 + 页面 + 日志）。\n现状：注册验证未配置；找回密码未接线（实测 400 RESET_PASSWORD_DISABLED）。\n验证：调用 `POST /main/api/auth/request-password-reset` 观察返回码。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.118",
  },
  {
    feature: "邮件",
    title: "缺工作流邮件节点的演示",
    description: "资料依据：app-plugin-workflow Skill + notification Skill（节点/通道集成）。\n应有演示：工作流里配置一个发送邮件的节点，触发后可在通知日志看到记录。\n现状：模板没有邮件节点示例。\n验证：打开工作流编辑器查看可用节点与示例工作流。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.130",
  },
  {
    feature: "邮件",
    title: "缺真实 SMTP 的集成测试",
    description: "资料依据：delivery-diagnostics.md（投递诊断）。\n应有演示：一个可复现的集成测试或手册，验证真实 SMTP 的投递与失败诊断。\n现状：没有真实 SMTP 测试。\n验证：按文档搭建本地 SMTP（如 MailHog）跑一次发送与诊断。",
    type: "example",
    status: "pending",
    owner: "陆建浩",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.143",
  },
  {
    feature: "多语言",
    title: "缺服务端翻译的演示（server/locales 为空对象）",
    description: "资料依据：app-plugin-i18n Skill（服务端文案）、cn/app/i18n.md。\n应有演示：服务端产生的文案（错误、通知、后台任务）随语言切换。\n现状：`server/locales` 是空对象，服务端翻译零演示。\n验证：切到中文后触发一个服务端错误，观察消息语言。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.155",
  },
  {
    feature: "多语言",
    title: "缺服务端回退与提示的演示（两端语言一致，只能靠单测）",
    description: "资料依据：i18n Skill（回落链、服务端不支持时的提示）。\n应有演示：客户端存在服务端不支持的语言时，界面给出提示并按英文回退。\n现状：两端语言一致，只能靠单测覆盖该行为。\n验证：临时在客户端加一个服务端没有的语言，切换后观察提示。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.167",
  },
  {
    feature: "多语言",
    title: "缺复数/缺翻译 fallback/RTL 的演示",
    description: "资料依据：i18n Skill（复数、缺翻译回退、格式化）。\n应有演示：应用自有复数形式、缺失翻译的回退结果，以及 RTL/多区域格式中的至少一种。\n现状：模板没有这些演示。\n验证：新增一个带 count 的 key 并切换语言观察。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.178",
  },
  {
    feature: "多语言",
    title: "缺默认语言配置的演示（需改配置才可见）",
    description: "资料依据：i18n Skill（defaultLocale）、AGENTS.md（config.yml 配置）。\n应有演示：在 `config.yml` 设置 `i18n.defaultLocale` 后，新会话按该语言启动。\n现状：需要改配置才能看到效果，模板未演示或说明。\n验证：改 `i18n.defaultLocale` 重启，用无痕窗口打开。",
    type: "example",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.190",
  },
  {
    feature: "日志",
    title: "缺运行日志查看器（Examples/Default 都没有，只有 Hub 有）",
    description: "资料依据：@nocobase/logging README（文件日志）、Hub 的 log-viewer。\n应有演示：应用内可查看 `storage/logs/` 的运行日志（或明确说明只在 Hub 提供）。\n现状：Examples 与 Default 都没有查看器，只有 Hub 有 `log-viewer.tsx`。\n验证：在 Examples 设置页查找日志入口。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.203",
  },
  {
    feature: "日志",
    title: "缺 DEBUG 调级演示",
    description: "资料依据：@nocobase/logging README（请求开始与配置加载用 DEBUG）。\n应有演示：把 `logging.level` 调到 debug 后能看到请求开始/配置加载等细节日志。\n现状：模板没有演示或说明。\n验证：改 `logging.level: debug` 重启，观察终端与文件输出。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.214",
  },
  {
    feature: "日志",
    title: "缺轮转/上限/脱敏的可操作演示（只有库单测）",
    description: "资料依据：@nocobase/logging README（轮转、留存、脱敏规则）。\n应有演示：制造足量日志观察轮转与总量上限，并验证敏感字段被脱敏。\n现状：只有库单测覆盖。\n验证：写大量日志后检查 `storage/logs/` 文件切分与保留。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.226",
  },
  {
    feature: "日志",
    title: "缺 README 对 storage/logs 的说明",
    description: "资料依据：@nocobase/logging README（应用强制使用持久 storage/logs）。\n应有演示：模板 README 说明日志目录、文件命名与保留策略。\n现状：README 未说明。\n验证：阅读 README 查找日志章节。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.238",
  },
  {
    feature: "日志",
    title: "缺运行日志与通知/工作流日志的区分说明",
    description: "资料依据：logging README + workflow/notification 文档。\n应有演示：文档或页面明确区分“运行日志（文件）”“工作流日志（落库）”“通知日志（落库）”。\n现状：运行日志按设计不落库，容易与另外两类混淆。\n验证：对照三处日志的存储位置与查看入口。",
    type: "example",
    status: "pending",
    owner: "陈庚扬",
    createdAt: "2026-09-21T15:42:13.557",
    updatedAt: "2026-09-22T15:17:30.250",
  },
  {
    feature: "应用搭建",
    title: "组合根（runtime/routes）演示",
    description: "已演示：`client/runtime.ts`、`server/runtime.ts`、`client/routes.ts` 为显式组合根，插件、Provider、路由均在此声明。\n资料依据：app-development Skill、client/server AGENTS。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.705",
  },
  {
    feature: "应用搭建",
    title: "路由与覆盖层演示",
    description: "已演示：`client/routes.ts:33-101` 与 `client/pages/route-overlays/` 覆盖 URL 可寻址的对话框/抽屉（RouteDialog/RouteDrawer）。\n资料依据：client-child-routes.md、client AGENTS（覆盖层规则）。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.718",
  },
  {
    feature: "应用搭建",
    title: "应用自有工作流演示",
    description: "已演示：`server/workflows/` 有 3 个应用自有工作流定义。\n资料依据：app-plugin-workflow Skill。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.732",
  },
  {
    feature: "应用搭建",
    title: "示例插件演示",
    description: "已演示：模板注册了 11 个 app-plugin-*-example（database/repository/routes/queue/realtime/service-provider/skills/file/authorization 等）。\n资料依据：README.MD#Plugins、server/plugins.ts、client/plugins.ts。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.745",
  },
  {
    feature: "应用搭建",
    title: "服务端示例齐全",
    description: "已演示：scheduler/queue/realtime/service-provider 均有服务端示例（如 `server/providers/scheduled-log-job.ts`）。\n资料依据：services-and-jobs.md、app-plugin-scheduler Skill。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.757",
  },
  {
    feature: "数据库",
    title: "迁移 + 种子演示",
    description: "已演示：`database/main/` 含迁移与种子，启动自动执行（config.yml migrations/seeds autoRun）。\n资料依据：migrations.md。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.830",
  },
  {
    feature: "数据库",
    title: "独立连接演示（analytics）",
    description: "已演示：`server/config/database.ts` 声明 analytics 连接，`database/analytics/*` 有迁移/种子，`server/routes/analytics.ts` 提供读写接口。\n资料依据：database-connections.md（多连接）。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.842",
  },
  {
    feature: "数据库",
    title: "外部只读连接演示（externalCrm）",
    description: "已演示：`database/externalCrm/collections/*` + metadata.json 描述外部只读连接，模板可查询该连接。\n资料依据：database-connections.md（external 连接）。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.855",
  },
  {
    feature: "数据库",
    title: "Repository 全能力演示",
    description: "已演示：`app-plugin-repository-example` 覆盖 Repository 的 CRUD、关联、事务等能力。\n资料依据：database-and-data.md。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.868",
  },
  {
    feature: "数据库",
    title: "Query vs Repository 对比演示",
    description: "已演示：`/numeric-examples` 页面与 `server/providers/numeric-examples-service.ts` 展示查询构建器与 Repository 的差异。\n资料依据：database-and-data.md。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.881",
  },
  {
    feature: "数据库",
    title: "Database Explorer 设置页演示",
    description: "已演示：设置页内可浏览连接、集合与字段（只读）。\n资料依据：app-plugin-database-explorer Skill。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.894",
  },
  {
    feature: "数据库",
    title: "迁移回滚验证演示",
    description: "已演示：可执行迁移的 up/down 并核对表结构（模板提供迁移示例，回滚验证在测试/文档中）。\n资料依据：migrations.md#Verify。",
    type: "example",
    status: "verified",
    owner: "陈霖",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T14:46:09.907",
  },
  {
    feature: "认证",
    title: "登录/登出/注册演示",
    description: "已演示：`/login`、`/register` 页面与登录登出流程可用。\n资料依据：cn/capabilities/auth/*。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.771",
  },
  {
    feature: "认证",
    title: "忘记/重置密码页演示",
    description: "已演示：`/forgot-password`、`/reset-password` 页面存在且可提交。\n资料依据：cn/capabilities/auth/*。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.784",
  },
  {
    feature: "认证",
    title: "auth guard 演示（guest/required）",
    description: "已演示：未登录访问受保护页跳转登录，已登录访问 guest 页跳转首页。\n资料依据：protecting-routes.md。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.797",
  },
  {
    feature: "认证",
    title: "会话存库演示",
    description: "已演示：`config.yml` 中 `auth.session.storeSessionInDatabase: true`，会话可在库中查看。\n资料依据：authentication Skill。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.809",
  },
  {
    feature: "认证",
    title: "API Keys 演示",
    description: "已演示：设置 → API Keys 可创建/删除 key，脚本可用 `x-api-key` 调用接口。\n资料依据：app-plugin-api-keys Skill。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.825",
  },
  {
    feature: "认证",
    title: "初始管理员 seed 演示",
    description: "已演示：首次启动按 `users.initialAdmin` 创建管理员（默认 nocobase/admin123）。\n资料依据：authentication Skill（初始管理员）。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.836",
  },
  {
    feature: "授权",
    title: "授权完整业务演示（authorization-example）",
    description: "已演示：`app-plugin-authorization-example` 提供 4 个页面、字段白名单、行级 scope、团队共享与三类规则种子（账号 sales_* / AuthzExample123!）。\n资料依据：app-plugin-authorization Skill。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.849",
  },
  {
    feature: "授权",
    title: "权限集/用户管理/Inspector 注册演示",
    description: "已演示：设置页可管理权限集、用户与 Inspector 查验。\n资料依据：runtime-api.md、cn/capabilities/authorization/*。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.862",
  },
  {
    feature: "授权",
    title: "页面拒绝与 authz: 'skip' 演示",
    description: "已演示：页面可按权限拒绝访问，`authz: 'skip'` 页面不受权限影响。\n资料依据：client AGENTS（authz 规则）。",
    type: "example",
    status: "verified",
    owner: "杨洽",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.875",
  },
  {
    feature: "文件",
    title: "文件关联演示（附件/头像/订单）",
    description: "已演示：`/file-repository` 三页覆盖单文件、1:1 头像与 1:N 订单附件。\n资料依据：app-plugin-file Skill。",
    type: "example",
    status: "verified",
    owner: "龚诚",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.887",
  },
  {
    feature: "文件",
    title: "预览格式矩阵演示",
    description: "已演示：位图/PDF/文本/音视频内置预览，DOCX/XLSX/PPTX 本地渲染（@silurus/ooxml）。\n资料依据：app-plugin-file Skill（预览矩阵）。",
    type: "example",
    status: "verified",
    owner: "龚诚",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.900",
  },
  {
    feature: "文件",
    title: "缩略图演示（前端）",
    description: "已演示：列表与预览使用前端按原图缩放生成缩略展示。\n资料依据：app-plugin-file Skill。",
    type: "example",
    status: "verified",
    owner: "龚诚",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.913",
  },
  {
    feature: "AI 员工",
    title: "AI 插件注册演示",
    description: "已演示：AI 员工插件已在 client/server 注册，设置页可管理。\n资料依据：app-plugin-ai-employee Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.927",
  },
  {
    feature: "AI 员工",
    title: "AI 管理页演示",
    description: "已演示：设置 → AI（Employees/Skills/Tools/Conversations）可用。\n资料依据：app-plugin-ai-employee Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.940",
  },
  {
    feature: "AI 员工",
    title: "开发态组件演示",
    description: "已演示：`/dev/ai-components/*` 组件演示页；配置 LLM 后可真实对话。\n资料依据：ai-employee Skill（frontend-registry）。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.952",
  },
  {
    feature: "AI 员工",
    title: "内置员工 Atlas 演示",
    description: "已演示：源码内置 Atlas 员工，启动即可见。\n资料依据：ai-employee Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.965",
  },
  {
    feature: "AI 员工",
    title: "LLM 服务接入演示",
    description: "已演示：`config.yml` 写入 dashscope-test（qwen3.7-flash + text-embedding-v4），启动日志 llmServices:1，可真实调用。\n资料依据：ai-employee Skill（LLM service configuration）。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.977",
  },
  {
    feature: "邮件",
    title: "通知运行时与 Provider 注册演示",
    description: "已演示：通知运行时与 Email/IM Provider 定义已注册。\n资料依据：app-plugin-notification Skill。",
    type: "example",
    status: "verified",
    owner: "陆建浩",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:33.990",
  },
  {
    feature: "邮件",
    title: "通知日志与测试发送演示",
    description: "已演示：设置 → 通知日志页常驻“Send test notification”，并展示通知/投递记录。\n资料依据：delivery-diagnostics.md。",
    type: "example",
    status: "verified",
    owner: "陆建浩",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.002",
  },
  {
    feature: "邮件",
    title: "In-app 链路演示",
    description: "已演示：站内信可走通“发送 → 收件箱 → 日志”。\n资料依据：app-plugin-notification-in-app Skill。",
    type: "example",
    status: "verified",
    owner: "陆建浩",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.015",
  },
  {
    feature: "多语言",
    title: "双语文案演示",
    description: "已演示：`client/locales/{en-US,zh-CN}.ts` 双端文件，类型由英文推导保证键一致。\n资料依据：app-plugin-i18n Skill。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.028",
  },
  {
    feature: "多语言",
    title: "语言切换器演示",
    description: "已演示：账号菜单语言切换器（含禁用/隐藏逻辑）。\n资料依据：i18n Skill、client AGENTS。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.040",
  },
  {
    feature: "多语言",
    title: "切换持久化与服务端同步演示",
    description: "已演示：切换语言写入本地存储并通知服务端（POST /api/i18n/locale）。\n资料依据：i18n Skill。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.054",
  },
  {
    feature: "多语言",
    title: "overrides 演示",
    description: "已演示：Examples 独有的插件文案覆盖（overrides）示例。\n资料依据：i18n Skill（覆盖插件文案）。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.067",
  },
  {
    feature: "多语言",
    title: "插值/格式化/i18n:check 演示",
    description: "已演示：插值、Intl 日期数字格式化，以及 `pnpm nocobase app i18n:check` 清单检查。\n资料依据：i18n Skill。",
    type: "example",
    status: "verified",
    owner: "曾煌尧",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.079",
  },
  {
    feature: "日志",
    title: "日志配置演示",
    description: "已演示：`server/config/logging.ts` 配置 file + console + request 分流。\n资料依据：@nocobase/logging README。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.090",
  },
  {
    feature: "日志",
    title: "请求日志演示",
    description: "已演示：请求日志中间件把 HTTP 记录写入 `storage/logs/request.<date>.log`。\n资料依据：@nocobase/logging README。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.101",
  },
  {
    feature: "日志",
    title: "工作流日志演示",
    description: "已演示：工作流节点日志落库，运行详情页可查看。\n资料依据：app-plugin-workflow Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.113",
  },
  {
    feature: "日志",
    title: "通知日志演示",
    description: "已演示：设置 → 通知日志页展示通知与投递记录。\n资料依据：app-plugin-notification Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.125",
  },
  {
    feature: "日志",
    title: "主动打日志演示",
    description: "已演示：`server/providers/scheduled-log-job.ts` 定时任务主动写日志。\n资料依据：@nocobase/logging README、app-plugin-scheduler Skill。",
    type: "example",
    status: "verified",
    owner: "陈庚扬",
    createdAt: "2026-09-21T22:19:43.063",
    updatedAt: "2026-09-22T15:20:34.137",
  },
  {
    feature: "应用搭建",
    title: "缺官网文档的插件开发 / Skills 同步 / CLI 参考（页面仍是占位）",
    description: "资料依据：官网文档 cn/plugin-development/*（quick-start、skills、publishing、when-to-build、capabilities）、cn/reference/commands.md、cn/reference/configuration.md。\n应有内容：插件注册/卸载/更新、Skills 同步、自定义 CLI 命令、配置参考等主流程说明。\n现状：这些页面都只有「本页内容正在编写」的占位大纲，没有可照做的步骤。\n验证：打开对应页面确认内容为空。",
    type: "docs",
    status: "pending",
    owner: "曾煌尧",
    createdAt: "2026-09-22T15:06:13.584",
    updatedAt: "2026-09-22T15:17:30.262",
  },
];

const ACTIVITIES: readonly ActivitySeed[] = [
  {
    feature: "应用搭建",
    problemTitle: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 plugin:register/unregister 的“注册前→后”演示（示例插件已全部注册）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 skills:sync 的端到端演示（改插件 Skill → 同步到应用）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺自定义 CLI 命令的演示（cli/commands 无示例命令）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 build --tar / --target 的打包与跨平台演示（只有文字说明）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 route-overrides 与 registry-example 的演示（覆盖为空、示例未注册）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 queue / service-provider / realtime 的首页入口演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "数据库",
    problemTitle: "缺 collections 派生产物的演示（`collections:generate --check` 跑不起来）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "数据库",
    problemTitle: "缺非 SQLite 方言的演示（mysql/oracle/postgres 有依赖无配置）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "数据库",
    problemTitle: "缺 database-example 的界面演示（只有迁移与种子）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "数据库",
    problemTitle: "缺编译清单（.manifest.json）的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺找回密码的实际发送演示（接口返回 400 RESET_PASSWORD_DISABLED）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺邮箱验证/邀请的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺用户自助的多设备会话管理演示（现仅管理员“撤销全部”）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺 SSO/OIDC 的可用演示（组件已物化但零引用）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺 auth: 'optional' 路由的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺登录态修改密码的界面演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "认证",
    problemTitle: "缺 install 向导的演示（被预填 secret 绕过）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "授权",
    problemTitle: "缺模板自有 API 的授权演示（只有 auth.required()）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "授权",
    problemTitle: "缺普通注册用户的可用角色演示（member 权限集 grants 为空）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "授权",
    problemTitle: "缺“改授权→另一会话立即生效”的可操作演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "授权",
    problemTitle: "缺安全事件审计查询的演示（事件只写文件）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "授权",
    problemTitle: "缺未授权场景的 e2e 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺非本地存储盘的演示（s3 为空占位，无 OSS/COS 驱动）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺附件/存储管理页（v3 已明确移除，属设计变更）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺服务端缩略图的演示（现仅前端原图缩放）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺旧版 DOC/XLS/PPT 与 ODF 的本地预览演示（仅下载）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺 Examples 预置的 file component-ui 扩展（Default 有但未被引用）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "文件",
    problemTitle: "缺文件 API 的鉴权示例（当前公开）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺生产态聊天入口的成品演示（三模板都未物化 AI Registry）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺示例员工/技能/MCP 的数据演示（ai/ 只有 .gitkeep）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺首页/README 的 AI 能力条目",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺可默认跑通的 AI e2e（现默认 skip 且员工名不符）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺发布产物包含 ai/ 骨架的保证（files 未含 ai/ 与 tsconfig.ai.json）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "AI 员工",
    problemTitle: "缺五种员工放置形态的成品页（只有文档与 dev 组件）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺 SMTP/Resend 的可跑配置（config.yml 里只有注释）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺业务代码调用通知服务的示例（无 notification.send() 调用）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺邮件模板/HTML/附件与 resolveUserEmail 的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺注册验证/找回密码邮件的演示（找回密码实测 400）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺工作流邮件节点的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "邮件",
    problemTitle: "缺真实 SMTP 的集成测试",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "多语言",
    problemTitle: "缺服务端翻译的演示（server/locales 为空对象）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "多语言",
    problemTitle: "缺服务端回退与提示的演示（两端语言一致，只能靠单测）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "多语言",
    problemTitle: "缺复数/缺翻译 fallback/RTL 的演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "多语言",
    problemTitle: "缺默认语言配置的演示（需改配置才可见）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "日志",
    problemTitle: "缺运行日志查看器（Examples/Default 都没有，只有 Hub 有）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "日志",
    problemTitle: "缺 DEBUG 调级演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "日志",
    problemTitle: "缺轮转/上限/脱敏的可操作演示（只有库单测）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "日志",
    problemTitle: "缺 README 对 storage/logs 的说明",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "日志",
    problemTitle: "缺运行日志与通知/工作流日志的区分说明",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-21T15:42:13.557",
  },
  {
    feature: "应用搭建",
    problemTitle: "组合根（runtime/routes）演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "应用搭建",
    problemTitle: "路由与覆盖层演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "应用搭建",
    problemTitle: "应用自有工作流演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "应用搭建",
    problemTitle: "示例插件演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "应用搭建",
    problemTitle: "服务端示例齐全",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "迁移 + 种子演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "独立连接演示（analytics）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "外部只读连接演示（externalCrm）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "Repository 全能力演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "Query vs Repository 对比演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "Database Explorer 设置页演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "数据库",
    problemTitle: "迁移回滚验证演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "登录/登出/注册演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "忘记/重置密码页演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "auth guard 演示（guest/required）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "会话存库演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "API Keys 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "认证",
    problemTitle: "初始管理员 seed 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "授权",
    problemTitle: "授权完整业务演示（authorization-example）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "授权",
    problemTitle: "权限集/用户管理/Inspector 注册演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "授权",
    problemTitle: "页面拒绝与 authz: 'skip' 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "文件",
    problemTitle: "文件关联演示（附件/头像/订单）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "文件",
    problemTitle: "预览格式矩阵演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "文件",
    problemTitle: "缩略图演示（前端）",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "AI 员工",
    problemTitle: "AI 插件注册演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "AI 员工",
    problemTitle: "AI 管理页演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "AI 员工",
    problemTitle: "开发态组件演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "AI 员工",
    problemTitle: "内置员工 Atlas 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "AI 员工",
    problemTitle: "LLM 服务接入演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "邮件",
    problemTitle: "通知运行时与 Provider 注册演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "邮件",
    problemTitle: "通知日志与测试发送演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "邮件",
    problemTitle: "In-app 链路演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "多语言",
    problemTitle: "双语文案演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "多语言",
    problemTitle: "语言切换器演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "多语言",
    problemTitle: "切换持久化与服务端同步演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "多语言",
    problemTitle: "overrides 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "多语言",
    problemTitle: "插值/格式化/i18n:check 演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "日志",
    problemTitle: "日志配置演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "日志",
    problemTitle: "请求日志演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "日志",
    problemTitle: "工作流日志演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "日志",
    problemTitle: "通知日志演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "日志",
    problemTitle: "主动打日志演示",
    kind: "created",
    actorName: "system",
    fromStatus: null,
    toStatus: "verified",
    createdAt: "2026-09-21T22:19:43.063",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    kind: "status",
    actorName: "陈霖",
    fromStatus: "pending",
    toStatus: "fixing",
    createdAt: "2026-09-22T09:12:00.000",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    kind: "status",
    actorName: "杨洽",
    fromStatus: "fixing",
    toStatus: "regression",
    createdAt: "2026-09-22T14:40:00.000",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    kind: "status",
    actorName: "龚诚",
    fromStatus: "regression",
    toStatus: "pending",
    createdAt: "2026-09-22T16:05:00.000",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺 create-app 三模板的运行演示（建完即可跑的入口）",
    kind: "status",
    actorName: "陈霖",
    fromStatus: "pending",
    toStatus: "fixing",
    createdAt: "2026-09-23T10:20:00.000",
  },
  {
    feature: "应用搭建",
    problemTitle: "缺官网文档的插件开发 / Skills 同步 / CLI 参考（页面仍是占位）",
    kind: "created",
    actorName: "nocobase",
    fromStatus: null,
    toStatus: "pending",
    createdAt: "2026-09-22T15:06:13.584",
  },
];

const seed: SeedDefinition = defineSeed({
  name: '202609220007_seed_curated_tracker_snapshot',

  async run({ query }) {
    await query.deleteFrom('problemComments').allowAllRows().execute();
    await query.deleteFrom('problemActivities').allowAllRows().execute();
    await query.deleteFrom('issues').allowAllRows().execute();
    await query.deleteFrom('featurePoints').allowAllRows().execute();

    const idByName = new Map<string, number>();
    const insertFeature = async (feature: FeatureSeed): Promise<void> => {
      const parentId =
        feature.level === 'dimension'
          ? null
          : (idByName.get(feature.dimension ?? '') ?? null);
      if (feature.level === 'feature' && parentId === null) {
        throw new Error(`Snapshot parent is missing: ${feature.name}`);
      }
      const result = await query
        .insertInto('featurePoints')
        .values({
          name: feature.name,
          level: feature.level,
          parentId,
          owner: feature.owner,
          skillsStatus: feature.skillsStatus,
          docsStatus: feature.docsStatus,
          exampleExists: feature.exampleExists,
          exampleExpected: feature.exampleExpected,
          exampleCurrent: feature.exampleCurrent,
          status: feature.status,
          designScore: feature.designScore,
          designNote: feature.designNote,
          developmentScore: feature.developmentScore,
          developmentNote: feature.developmentNote,
          agentFriendlinessScore: feature.agentFriendlinessScore,
          agentFriendlinessNote: feature.agentFriendlinessNote,
          outputQualityScore: feature.outputQualityScore,
          outputQualityNote: feature.outputQualityNote,
          remark: feature.remark,
          sortOrder: feature.sortOrder,
          createdAt: new Date(),
          updatedAt: new Date(),
        })
        .execute();
      idByName.set(feature.name, Number(result.insertId));
    };

    for (const feature of FEATURES) {
      if (feature.level === 'dimension') await insertFeature(feature);
    }
    for (const feature of FEATURES) {
      if (feature.level === 'feature') await insertFeature(feature);
    }

    const problemIdByKey = new Map<string, number>();
    for (const problem of PROBLEMS) {
      const featurePointId = idByName.get(problem.feature);
      if (featurePointId === undefined) {
        throw new Error(`Snapshot feature point is missing: ${problem.feature}`);
      }
      const result = await query
        .insertInto('issues')
        .values({
          title: problem.title,
          description: problem.description,
          featurePointId,
          type: problem.type,
          status: problem.status,
          owner: problem.owner,
          createdAt: new Date(problem.createdAt),
          updatedAt: new Date(problem.updatedAt),
        })
        .execute();
      problemIdByKey.set(
        `${problem.feature}::${problem.title}`,
        Number(result.insertId),
      );
    }

    for (const activity of ACTIVITIES) {
      const problemId = problemIdByKey.get(
        `${activity.feature}::${activity.problemTitle}`,
      );
      if (problemId === undefined) continue;
      await query
        .insertInto('problemActivities')
        .values({
          problemId,
          // Actor ids belong to the database this snapshot came from; the name is
          // what the timeline displays, so it is carried without a foreign id.
          actorId: null,
          actorName: activity.actorName,
          kind: activity.kind,
          fromStatus: activity.fromStatus,
          toStatus: activity.toStatus,
          createdAt: new Date(activity.createdAt),
        })
        .execute();
    }
  },
});

export default seed;
