// Generated by scripts/generate-evaluation-contracts.mjs from the pinned public schema.
export type Batch_repository = string;
export type Batch_segment = string;
export type Batch_sha = string;
export type Batch_optionalSha = string | null;
export type Batch_sha256 = string;
export type Batch_count = number;
export type Batch_sampleState =
  | 'planned'
  | 'queued'
  | 'running'
  | 'passed'
  | 'failed'
  | 'blocked'
  | 'budget-exhausted'
  | 'cancelled'
  | 'unknown';
export type EvaluationBatch = {
  schemaVersion: 1;
  type: 'evaluation-batch';
  source: {
    producer: 'nb3-factory';
    instance: Batch_repository;
    project: Batch_repository;
    exporter: {
      version: number;
      controlSha: Batch_optionalSha;
      runId: number | null;
      attempt: number | null;
    };
  };
  batch: {
    key: Batch_segment;
    subjectKey: string;
    planKey: string;
    planFingerprint: Batch_sha256;
    manifestSha256: Batch_sha256;
    trigger: 'manual' | 'schedule';
    slot: string | null;
    coordinatorIssue: number;
    frozenAt: string;
    sequence: number;
  };
  revision: number;
  createdAt: string;
  state: 'active' | 'completed' | 'cancelled';
  cancelled: boolean;
  baseline: {
    controlSha: Batch_sha;
    entrySha: Batch_optionalSha;
    applicationBaseSha: Batch_sha;
    defaultBranch: string;
    lockfileSha256: Batch_sha256;
    templateVersion: string | null;
    reviewMode: 'inherit' | 'full' | 'off';
    budget: {
      maxRepairAttempts: number;
      maxActiveSeconds: number;
      maxContinuations: number;
    };
    maxConcurrentSamples: 1;
    agentEngine: string;
    agentConfig: null | {
      fingerprint: Batch_sha256;
      values: { [key: string]: string };
    };
  };
  cases: Array<{
    key: string;
    presetIssueNumber: number;
    title: string;
    caseHash: Batch_sha256;
    capturedAt: string;
    commentCount: number;
    buildReviewMode: 'full' | 'off';
    samples: number;
  }>;
  samples: Array<{
    key: string;
    caseKey: string;
    sampleIndex: number;
    runKey: string;
    issue: number | null;
    state: Batch_sampleState;
    stateSource:
      'plan' | 'coordinator' | 'run' | 'report' | 'prepare' | 'batch';
    dispatchedAt: null | string;
    terminalAt: null | string;
    reason: string | null;
    agentConfigFingerprint: null | Batch_sha256;
    comparable: boolean | null;
    report: {
      state: 'available' | 'missing' | 'not-applicable';
      revision: number | null;
      execution:
        | 'running'
        | 'completed'
        | 'cancelled'
        | 'timed-out'
        | 'budget-exhausted'
        | 'blocked'
        | 'unknown'
        | null;
      acceptance:
        'passed' | 'failed' | 'blocked' | 'not-run' | 'unknown' | null;
    };
  }>;
  summary: {
    planned: number;
    byState: {
      planned: Batch_count;
      queued: Batch_count;
      running: Batch_count;
      passed: Batch_count;
      failed: Batch_count;
      blocked: Batch_count;
      'budget-exhausted': Batch_count;
      cancelled: Batch_count;
      unknown: Batch_count;
    };
    reports: {
      available: Batch_count;
      missing: Batch_count;
      notApplicable: Batch_count;
    };
    comparable: boolean;
    acceptance: {
      passed: Batch_count;
      failed: Batch_count;
      other: Batch_count;
    };
  };
  limitations: Array<{ code: string; detail: string }>;
};
