// Generated by scripts/generate-evaluation-contracts.mjs from the pinned public schema.
export type EvaluationBundle = {
  schemaVersion: 1;
  type: 'evaluation-bundle';
  subject: {
    type: 'evaluation-report' | 'evaluation-batch';
    key: string;
    revision: number;
    sourceInstance: string;
  };
  files: Array<{
    path: string;
    role: 'evaluation-report' | 'evaluation-batch' | 'report-html' | 'evidence';
    mediaType: 'application/json' | 'text/html' | 'image/png';
    size: number;
    sha256: string;
    evidenceIds?: Array<string>;
  }>;
};
