// Generated by scripts/generate-evaluation-contracts.mjs from the pinned public schema.
export type EvaluationReceipt = {
  receiptId: string;
  sourceInstance: string;
  runKey?: string;
  batchKey?: string;
  revision: number;
  bundleSha256: string;
  state: 'stored';
  [key: string]: unknown;
};
