// Generated by scripts/generate-evaluation-contracts.mjs from the pinned public schema.
export type Report_positive = number;
export type Report_count = number;
export type Report_optionalCount = number | null;
export type Report_repository = string;
export type Report_runKey = string;
export type Report_optionalSegment = string | null;
export type Report_optionalSha = string | null;
export type Report_optionalSha256 = string | null;
export type Report_optionalTime = null | string;
export type Report_optionalText = string | null;
export type Report_text = string;
export type Report_coverage = 'complete' | 'partial' | 'none';
export type Report_qaStatus =
  'passed' | 'failed' | 'blocked' | 'not-run' | 'unknown';
export type Report_reviewState =
  'completed' | 'partial' | 'not-reviewed' | 'failed';
export type Report_scopedId = string;
export type Report_scopedIds = Array<Report_scopedId>;
export type Report_limitations = Array<{ code: string; detail: string }>;
export type Report_source = {
  producer: 'nb3-factory';
  instance: Report_repository;
  project: Report_repository;
  exporter: {
    version: Report_positive;
    controlSha: Report_optionalSha;
    runId: number | null;
    attempt: number | null;
  };
};
export type Report_baseline = {
  track: 'published-template' | 'source-snapshot';
  application: {
    baseRef: string | null;
    baseSha: Report_optionalSha;
    candidate: {
      patchSha256: Report_optionalSha256;
      headSha: Report_optionalSha;
    };
  };
  factory: { controlSha: Report_optionalSha; entrySha: Report_optionalSha };
  template: { creatorVersion: string | null; templateVersion: string | null };
  dependencies: {
    lockfileSha256: Report_optionalSha256;
    baselineFingerprint: Report_optionalSha256;
    packages: Array<{ name: string; version: string | null }>;
  };
  skills: { fingerprint: Report_optionalSha256; files: Report_count };
  sourceSnapshot: null | { repository: string | null; sha: string };
  inputs: {
    taskInputHash: Report_optionalSha256;
    pipelineInputHash: Report_optionalSha256;
    reviewHash: Report_optionalSha256;
    reviewCriteriaHash: Report_optionalSha256;
    prompts: Array<{ phase: string; path: string; sha256: string }>;
  };
  rubric: null | { id: 'nb3-framework'; version: 1 | 2 };
  agent: {
    engine: string | null;
    model: string | null;
    version: string | null;
    buildReviewMode: 'full' | 'off' | null;
  };
  environment: {
    browserFixturesSha256: Report_optionalSha256;
    browserPreflight: 'passed' | 'failed' | null;
  };
};
export type Report_execution = {
  key: Report_scopedId;
  kind:
    | 'implementation'
    | 'continuation'
    | 'recovery'
    | 'restart'
    | 'rerun-attempt'
    | 'review';
  order: Report_positive;
  workflow: 'code-agent-task' | 'reassess-build-quality';
  runId: Report_positive;
  attempt: Report_positive;
  event: 'issues' | 'repository_dispatch' | 'workflow_dispatch' | null;
  previousRunId: number | null;
  conclusion:
    | 'delivered'
    | 'handoff'
    | 'failed'
    | 'cancelled'
    | 'timed-out'
    | 'completed'
    | 'budget-exhausted'
    | 'blocked'
    | 'unknown';
  startedAt: Report_optionalTime;
  endedAt: Report_optionalTime;
  jobSeconds: Report_optionalCount;
  controlSha: Report_optionalSha;
  patchSha256: Report_optionalSha256;
  source: 'usage-receipt' | 'build-review';
};
export type Report_fullRun = {
  status: Report_qaStatus;
  round: number | null;
  executionKey: null | Report_scopedId;
  basis: string;
};
export type Report_attemptCounts = {
  verificationAttempts: Report_optionalCount;
  repairAttempts: Report_optionalCount;
  source: string;
};
export type Report_qa = {
  coverage: Report_coverage;
  rounds: Array<{
    round: Report_positive;
    executionKey: Report_scopedId;
    scope: 'full' | 'focused';
    passed: boolean | null;
    source: string;
    checks: Array<{
      id: string | null;
      criterion: string | null;
      status: Report_qaStatus;
      evidence: Report_scopedIds;
    }>;
  }>;
  firstFull: Report_fullRun;
  finalFull: Report_fullRun;
  criteria: Array<{
    id: string;
    text: string;
    optional: boolean;
    firstFull: Report_qaStatus;
    finalFull: Report_qaStatus;
  }>;
  firstPassWithoutRepair: 'yes' | 'no' | 'unknown';
  counts: { execution: Report_attemptCounts; chain: Report_attemptCounts };
  note: string;
};
export type Report_score = {
  score: number | null;
  reason: Report_text;
  evidence: Report_scopedIds;
};
export type Report_module = {
  key: Report_scopedId;
  name: string;
  subjectKeys: Array<string>;
  mapping: 'resolved' | 'pending';
  targets: Array<{
    kind: 'library' | 'plugin' | 'guidance';
    name: string;
    subjectKey: string | null;
    entrypoints: Array<string>;
    evidence: Report_scopedIds;
  }>;
  scope: Report_text;
  limitations: Report_text;
  criteria: Array<string>;
  qa: { firstFull: Report_qaStatus; finalFull: Report_qaStatus };
  requirements: Array<{
    need: Report_text;
    responsibility: Report_text;
    support:
      | 'direct'
      | 'composition'
      | 'workaround'
      | 'missing'
      | 'unknown'
      | 'out-of-scope';
    recommendedUsage: Report_text;
    actualUsage: Report_text;
    gapOwner:
      | 'none'
      | 'framework'
      | 'plugin'
      | 'template'
      | 'documentation'
      | 'application'
      | 'factory'
      | 'environment'
      | 'unknown';
    evidence: Report_scopedIds;
  }>;
  scores: { [key: string]: Report_score };
};
export type Report_finding = {
  id: Report_scopedId;
  localId: string;
  kind: 'strength' | 'issue' | 'misleading' | 'improvement';
  owner:
    | 'framework'
    | 'plugin'
    | 'template'
    | 'documentation'
    | 'application'
    | 'factory'
    | 'environment'
    | 'unknown';
  severity: 'info' | 'minor' | 'major' | 'critical';
  confidence: 'confirmed' | 'suspected';
  confirmedBy: 'reviewer' | null;
  reviewerStatus: 'open' | 'resolved' | 'unknown' | 'not-applicable';
  title: Report_text;
  detail: Report_text;
  impact: Report_text;
  suggestedChange: Report_text;
  claimed: Report_optionalText;
  observed: Report_optionalText;
  evidence: Report_scopedIds;
  moduleKeys: Report_scopedIds;
  subjectKeys: Array<string>;
};
export type Report_review = {
  key: Report_scopedId;
  role: 'original' | 'supplement' | 'legacy';
  selected: boolean;
  state: Report_reviewState;
  reason: string;
  rubric: null | {
    id: 'nb3-framework';
    version: 1 | 2;
    scale: { min: 0; max: 100 };
    businessUiIncluded: false;
    dimensions: Array<{ key: string; label: string }>;
  };
  reviewer: null | {
    engine: string | null;
    model: string | null;
    version: string | null;
    runId: number | null;
    attempt: number | null;
    controlSha: Report_optionalSha;
    replay: boolean;
  };
  producer: { runId: number | null; attempt: number | null };
  basis: {
    inputHash: Report_optionalSha256;
    patchSha256: Report_optionalSha256;
    baseSha: Report_optionalSha;
    lockfileSha256: Report_optionalSha256;
    reviewCriteriaHash: Report_optionalSha256;
    artifactHash: Report_optionalSha256;
  };
  buildReviewMode: 'full' | 'off' | null;
  summary: Report_optionalText;
  progress: null | { complete: boolean; pendingModules: Array<string> };
  modules: Array<Report_module>;
  findings: Array<Report_finding>;
  ui: null | {
    status: 'reviewed' | 'not-reviewed';
    score: number | null;
    reason: Report_text;
    evidence: Report_scopedIds;
    framework: false;
  };
  limitations: Array<string>;
  usageSource: string | null;
};
export type Report_processNotes = {
  state: 'present' | 'absent' | 'invalid';
  source: 'retro.json' | null;
  author: 'implementer';
  independent: false;
  summary: Report_optionalText;
  blockers: Array<{
    id: Report_scopedId;
    phase: string | null;
    title: string;
    symptom: Report_optionalText;
    rootCause: Report_optionalText;
    resolution: Report_optionalText;
    cost: string | null;
    status: 'resolved' | 'open' | 'unknown';
  }>;
  improvements: Array<{
    id: Report_scopedId;
    category: string | null;
    title: string;
    detail: Report_optionalText;
    suggestedChange: Report_optionalText;
    mechanizable: boolean;
  }>;
  note: string;
};
export type Report_tokens = {
  input: Report_optionalCount;
  output: Report_optionalCount;
  cacheRead: Report_optionalCount;
  cacheWrite: Report_optionalCount;
  total: Report_optionalCount;
};
export type Report_metrics = {
  usage: {
    sources: Array<{
      key: string;
      executionKey: Report_scopedId;
      scope: string;
      phases: {
        implementation: Report_tokens;
        repair: Report_tokens;
        qa: Report_tokens;
        qaFocused: Report_tokens;
        qaReport: Report_tokens;
        review: Report_tokens;
        compaction: Report_tokens;
      };
      records: Report_count;
      missing: Report_count;
      incomplete: Report_count;
      complete: boolean;
    }>;
    totals: {
      input: Report_optionalCount;
      output: Report_optionalCount;
      cacheRead: Report_optionalCount;
      cacheWrite: Report_optionalCount;
      total: Report_optionalCount;
      complete: boolean;
    };
    definition: string;
  };
  time: {
    executionSeconds: Report_optionalCount;
    missingJobTimes: Report_count;
    endToEndSeconds: Report_optionalCount;
    jobs: Array<{
      id: Report_positive;
      name: 'prepare' | 'agent' | 'verify-final' | 'publish';
      executionKey: Report_scopedId;
      seconds: Report_optionalCount;
    }>;
    definition: string;
  };
  counts: {
    businessBuilds: 1;
    executions: Report_count;
    reviewExecutions: Report_count;
  };
};
export type Report_evidence = {
  id: Report_scopedId;
  origin: { kind: 'review' | 'qa'; key: Report_scopedId; localId: string };
  kind: 'code' | 'package' | 'skill' | 'qa' | 'screenshot' | 'log';
  path: string;
  lines: null | Array<Report_positive>;
  sha256: Report_optionalSha256;
  observation: Report_text;
  excerpt: string | null;
  excerptRedacted: boolean;
  attachment: string | null;
  availability: 'attached' | 'excerpt' | 'reference-only';
  note: string | null;
};
export type EvaluationReport = {
  schemaVersion: 1;
  type: 'evaluation-report';
  source: Report_source;
  run: {
    key: Report_runKey;
    kind: 'initial' | 'incremental' | 'batch-sample';
    identity: 'recorded' | 'legacy-derived' | 'unresolved';
    batchKey: Report_optionalSegment;
    caseKey: Report_optionalSegment;
    sampleIndex: number | null;
    sampleKey: string | null;
    task: {
      repository: Report_repository;
      issue: Report_positive;
      buildCommentId: number | null;
      title: string;
    };
    case: null | {
      source: 'preset';
      presetIssueNumber: number | null;
      capturedAt: Report_optionalTime;
      inputHash: Report_optionalSha256;
      reviewHash: Report_optionalSha256;
    };
  };
  revision: Report_positive;
  createdAt: string;
  precedence: {
    producer: {
      runId: Report_positive;
      attempt: Report_positive;
      startedAt: Report_optionalTime;
    };
    executionOrder: number;
    knownLaterExecutions: number;
    chainTerminal: boolean;
    reviewRubric: 0 | 1 | 2;
    reviewState: Report_reviewState;
    review: {
      kind: 'build' | 'reassessment' | null;
      at: Report_optionalTime;
      runId: number | null;
      attempt: number | null;
    };
    qaCoverage: Report_coverage;
  };
  baseline: Report_baseline;
  executions: Array<Report_execution>;
  outcome: {
    execution:
      | 'running'
      | 'completed'
      | 'cancelled'
      | 'timed-out'
      | 'budget-exhausted'
      | 'blocked'
      | 'unknown';
    acceptance: 'passed' | 'failed' | 'blocked' | 'not-run' | 'unknown';
    delivery: 'published' | 'not-published' | 'unknown';
    pullRequest: null | {
      number: Report_positive;
      headSha: Report_optionalSha;
    };
    detail: string;
  };
  qa: Report_qa;
  reviews: Array<Report_review>;
  processNotes: Report_processNotes;
  metrics: Report_metrics;
  evidence: Array<Report_evidence>;
  links: Array<{
    rel:
      | 'task-issue'
      | 'run'
      | 'pull-request'
      | 'report-archive'
      | 'review-run'
      | 'batch';
    label: string;
    url: null | string;
    path: string | null;
  }>;
  limitations: Report_limitations;
};
